[package]
name = "flick-flightctrl"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
num-traits = "0.2"
nalgebra = "0.31.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
